### ISSUE TITLE
Shifting papers from CHIELD to ARCUS

### ISSUE THREAD

**Issue by angarikadeb** [CHIELDOnline/ARCUS#19]
Hey, could you please transfer the following papers from CHIELD to ARCUS:
Rebecca M Horne et al., 2018
Stephane Debove et al., 2015
Marieke Van Willingen & Patricia Drentea, 2001
Jeanne A Batalova & Cohen, 2002
Carolyn E Cutrona, 1986
Clifford L Broman, 1988
Lennon & Rosenfield, 1994
Theodore N Greenstein, 2000

**Comment by CHIELDOnline** [comment]
Done

**Comment by angarikadeb** [comment]
Thank youuu!
