### ISSUE TITLE
Correlation and colored arrows

### ISSUE THREAD

**Issue by angarikadeb** [CHIELDOnline/ARCUS#20]
Can we add blue and red highlights to the arrows for positive and negative correlations?
What I have in mind is: a blue highlight on top of the black one for positive correlations; a red highlight for negative correlations; the rest remain black like it is now. [I am a bit confused whether I should keep blue-pos and red-neg or make it the reverse. What makes more sense, color-wise?]

I also wanted to include a separate space for adding interaction effects (this is very relevant for the papers I am coding). It could be a separate block of rows, below the current block of rows that code main effects. Or any other way, which you think might be more efficient or easier to use.

**Comment by CHIELDOnline** [comment]
Re: interaction effects. From the supporting materials of our paper:

There doesn't appear to be a standard way of representing interactions in causal graphs (see e.g. the section on sufficient causation in VanderWeele & Robins, 2007). Technically, all arrows into a node define a joint conditional probability distribution, so information about the interaction is still encoded. But the graph doesn't look different, which some researchers find annoying.

In the case that the two contributing causes amplify each other, not much information is lost by just coding them as having simple links to the effect. However, when the presence of one effect reverses the effect of another, there seems to be some call to mark this somehow. In many cases the issue can be resolved by thinking about the extra steps in between. For example, imagine a paper on the spread of forms within a social network, where the time to convergence is affected by an non-linear interaction between content bias (how strong agent’s prior biases are) and population connectivity. You could add an extra node called "rate of dispersal”, which represents how quickly new items are transmitted around the network. This new node would be placed in between between:

content bias > rate of dispersal
population connectivity > rate of dispersal
rate of dispersal > time to convergence

"rate of dispersal" might not be an actual parameter in the paper, but it might be an implicit part of the explanation of why these things are connected. If in doubt, keep the structure simple, but add a note in the "Notes" column.

**Comment by CHIELDOnline** [comment]
Re: arrows: I'd like to reserve red hilights for non-significant effects. How about green for positive, blue for negative? (Or some similar colour-blind-safe pair)

**Comment by angarikadeb** [comment]
I see. Yes I hadnt thought about how exactly it will be represented in the causal graph and it does seem difficult. What you say makes sense, perhaps we could add some of these instructions in the help section - giving people (who want to code interactions too) some guidelines on how they can do it in causal graph

**Comment by angarikadeb** [comment]
And yes, bright green for positive and an indigo blue for negative sounds representative enough :)
That works 👍
