### ISSUE TITLE
Regarding columns

### ISSUE THREAD

**Issue by angarikadeb** [CHIELDOnline/ARCUS#21]
I was thinking of the following columns for ARCUS: 
1. Var1
2. Relation
3. Var2
4. Cor
5. Study Population (this will include sample size, source, etc - doesn’t need a drop down menu, but perhaps a description to cue people what they can put in?)
6. Subject/ Discipline (this would be good with drop-down: psychology, cognitive science, sociology, anthropology, economics, gender studies, philosophy, organizational studies, evolutionary studies, human behavioral ecology, linguistics, cultural evolution - these come to mind already and I think there are more. Is this too long for a drop-down?)
7. Type - (In this dropdown, could you please include ‘survey’ & ‘database analysis’ also? Though I realize, that database analysis would be of the statistical Type)
8. Tools & Analysis (this can include details of data collection tools, analytical methods and any details that the coder might want to include. So doesnt need any dropdown)
9. Notes (this is like that in CHIELD)

Additionally, I wanted to add a long column called ‘General Notes’, not separated by any row lines. This is for any general details about the paper itself, that the coder might find to be of interest and want to draw attention to. I find myself wanting to do that for quite a few papers. What do you think?

**Comment by CHIELDOnline** [comment]
(moved to separate issues)
