### ISSUE TITLE
Update List of Topics

### ISSUE THREAD

**Issue by angarikadeb** [CHIELDOnline/ARCUS#24]
Send a comprehensive list of updates to Sean to be added to the ‘Topics’ page on ARCUS

**Comment by CHIELDOnline** [comment]
The list of possible topics is actually drawn from a pre-determined hierarchy, here: https://github.com/CHIELDOnline/ARCUS/blob/master/data/tabular/topicHierarchy.tab

Any entries in the "topic" columns of causal link specifications will be added to the hierarchy. Topics not in the list will be added under "other".

**Comment by angarikadeb** [comment]
Ahh okay. So it depends on me, to put in the topics of the papers for now?
Might it be possible to write ‘subject’ instead of topics? I dont know why that sounds more relevant. But if not, no problem! There can always be instructions on what we mean by topic

**Comment by CHIELDOnline** [comment]
Yes, that's right. Ok, I'll change the title to "subject". (this will be done in the big update of columns)
