### ISSUE TITLE
Documents keep appearing and disappearing

### ISSUE THREAD

**Issue by angarikadeb** [CHIELDOnline/ARCUS#29]
Hi Sean

There is some problem with the website, such that it doesn't show all the documents at all times. Sometimes, it shows the complete list but at other times when I open ARCUS website, the documents list only shows half of the documents. This also means that many of the variables cannot be searched

Not sure what could be the problem. But since I am presenting ARCUS to my lab on Friday, I didn't want papers to be disappearing. Do you think you could find some time to have a quick look?

**Comment by CHIELDOnline** [comment]
Sorry, there was an error processing one of the files, so it stopped at that point and only compiled a portion of the data. In a few cases, the bibtex for the source has not been complete (missing a journal or a book titile). I should put a check in the add data page for this.
But the documents are back up.

**Comment by angarikadeb** [comment]
I think it has happened again: I edited some documents, changing variable names. After fetching and pushing origin on GitHub desktop, files have again disappeared. 

These were existing files, but should I have checked the bibtex for these? 
I will keep in mind, being cautious about the bibtex source for the new files that I add. Not sure what to do right now, for the files that have disappeared again.

Also, do you get a list of these files which have incomplete bibtex sources? Maybe I can fix these?

**Comment by CHIELDOnline** [comment]
The good news is that the files aren't disappearing from the repository, they're just not being added to the ARCUS.sqlite file. I suspect that when you run the processing script on your computer, there's some error and it does not update the ARCUS.sqlite file. So when you upload it to the server, you're just adding an old file.

You can either ask me to do the update, or we can try and figure out the problem. If the latter, can you: Pull the changes. Then run the "tree to database" script. Then reply to this issue with any errors that appear?

**Comment by CHIELDOnline** [comment]
(I re-ran the processing script and the database is up to date now)

**Comment by angarikadeb** [comment]
Great! It would be good to figure out the problem, so I dont have to bug you each time. I am editing some files now and will get back to you with the errors

**Comment by angarikadeb** [comment]
Yes, the documents have disappeared again This. This is what R shows, on running the script. 
![Uploading 20200915_202240.jpg…]()

**Comment by CHIELDOnline** [comment]
Sorry, I can't see the screenshot on github. Can you send it to me by email?
What I'd really like is a copy and paste of the console window after you run the R script.

**Comment by CHIELDOnline** [comment]
Error was that the R script was not updating the ARCUS.sqlite file after processing the raw data. Uploading it to the server overwrote Sean's copy.
