### ISSUE TITLE
Columns: Study population

### ISSUE THREAD

**Issue by CHIELDOnline** [CHIELDOnline/ARCUS#40]
>  Study Population (this will include sample size, source, etc - doesn’t need a drop down menu, but perhaps a description to cue people what they can put in?)

I think it makes sense to split up this information, so I need some more information on the details included here. e.g.:
-  Sample size: Text (though encouraged to use a number)
-  Source country: Text, encouraged to use a semi-colon separated list e.g. "USA;UK"
-  Source demographic: Free text, e.g. "undergraduate students"

All these could be optional, and the input cold be hidden by default and then pop-up as a little window if you want to add data.

The other option is just to have a single text field where you can paste a full quote from the paper on the sample of subjects. This could be searched or mined later.

**Comment by angarikadeb** [comment]
I think the former makes more sense - separating size, source country and demographic in our own format which pops up when the coder wants to add this data

**Comment by CHIELDOnline** [comment]
Number, location, demographic
	Copy to rest of cells

	Explore: Colour by sample 
		Show/hide edges by country
		Filter by country

**Comment by CHIELDOnline** [comment]
Now implemented.
