### ISSUE TITLE
Columns: Subject

### ISSUE THREAD

**Issue by CHIELDOnline** [CHIELDOnline/ARCUS#41]
>  Subject/ Discipline (this would be good with drop-down: psychology, cognitive science, sociology, anthropology, economics, gender studies, philosophy, organizational studies, evolutionary studies, human behavioral ecology, linguistics, cultural evolution - these come to mind already and I think there are more. Is this too long for a drop-down?)

This is what the "topic" field is for. It's linked to a hierarchy of predefined topics. I can rename the column, if you like. I can also add the current hierarchy as suggestions to the field?

**Comment by angarikadeb** [comment]
Yes to both the questions - renaming and providing suggestions for field.
Thanks :D

**Comment by CHIELDOnline** [comment]
Column name changed.
