### ISSUE TITLE
Columns: Tools & Analysis

### ISSUE THREAD

**Issue by CHIELDOnline** [CHIELDOnline/ARCUS#42]
>  Tools & Analysis (this can include details of data collection tools, analytical methods and any details that the coder might want to include. So doesnt need any dropdown)

Can you give me an example of an entry? How do you think users will use this information?

**Comment by angarikadeb** [comment]
For this, there can be three parts - 
**Analysis type:** this will be free text, specifying the name of analysis run or modeling type. Can be multiple entries separated by semicolon (e.g., bivariate regression; multiple regression).
**Tools:** free text specifying the softwares or tools used (I am a bit unsure if this one is necessary.
**Others details**: again free text, for inputting any other analysis details (e.g., comparing amount of housework done by men and women Or model 1 - empty, model 2 - variables.x & y, model 3 - x, y, z and x*z)

**Comment by CHIELDOnline** [comment]
Analysis type: Free text
	Analysis details: free text
	Stats: free text

**Comment by CHIELDOnline** [comment]
Now implemented.
