### ISSUE TITLE
Columns: General notes

### ISSUE THREAD

**Issue by CHIELDOnline** [CHIELDOnline/ARCUS#43]
>  I wanted to add a long column called ‘General Notes’, not separated by any row lines. This is for any general details about the paper itself, that the coder might find to be of interest and want to draw attention to. I find myself wanting to do that for quite a few papers. What do you think?

I'm tempted to add this to the bib file as the "notes" field. I'll make an easy way to add and view this info on the ARCUS website.

**Comment by angarikadeb** [comment]
But the notes are specifications for a single causal link right? I suppose you mean, the code for this will be merged, but general notes will be viewed separately?

**Comment by CHIELDOnline** [comment]
Now implemented. You can enter a general note on the "Reference" tab. It appears on the document page if there is a general note.
