### ISSUE TITLE
Colums: stats?

### ISSUE THREAD

**Issue by CHIELDOnline** [CHIELDOnline/ARCUS#60]
In the past, we've discussed adding a column that represents the strength of association between two variables (e.g. correlation, beta value). Are you still interested in this? I'd caution you to only include columns that you'll actually use.

**Comment by angarikadeb** [comment]
Send details of how the stats should look like and how effects are to be reported.
Column with free text or with prompt for standardized measures?

**Comment by CHIELDOnline** [comment]
Now implemented.
